package pango

import "github.com/gotk3/gotk3/pango/iface"

func init() {
  iface.AssertPango(&RealPango{})
  iface.AssertAttrClass(&AttrClass{})
  iface.AssertAttrColor(&AttrColor{})
  iface.AssertAttrFloat(&AttrFloat{})
  iface.AssertAttrFontDesc(&AttrFontDesc{})
  iface.AssertAttrInt(&AttrInt{})
  iface.AssertAttrLanguage(&AttrLanguage{})
  iface.AssertAttrList(&AttrList{})
  iface.AssertAttrShape(&AttrShape{})
  iface.AssertAttrSize(&AttrSize{})
  iface.AssertAttrString(&AttrString{})
  iface.AssertAttribute(&Attribute{})
  iface.AssertColor(&Color{})
  iface.AssertContext(&Context{})
  iface.AssertEngineLang(&EngineLang{})
  iface.AssertEngineShape(&EngineShape{})
  iface.AssertFont(&Font{})
  iface.AssertFontDescription(&FontDescription{})
  iface.AssertFontMap(&FontMap{})
  iface.AssertFontMetrics(&FontMetrics{})
  iface.AssertGlyphGeometry(&GlyphGeometry{})
  iface.AssertGlyphInfo(&GlyphInfo{})
  iface.AssertGlyphItem(&GlyphItem{})
  iface.AssertGlyphString(&GlyphString{})
  iface.AssertGlyphVisAttr(&GlyphVisAttr{})
  iface.AssertLayout(&Layout{})
  iface.AssertLayoutLine(&LayoutLine{})
  iface.AssertLogAttr(&LogAttr{})
  iface.AssertRealPango(&RealPango{})
  iface.AssertRectangle(&Rectangle{})
}
