package gtk

import (
	"github.com/gotk3/gotk3/cairo"
	"github.com/gotk3/gotk3/gdk"
	"github.com/gotk3/gotk3/glib"
)

type Gtk interface {
	AboutDialogNew() (AboutDialog, error)
	AccelGroupFromClosure(interface{}) AccelGroup
	AccelGroupNew() (AccelGroup, error)
	AccelGroupsActivate(glib.Object, uint, gdk.ModifierType) bool
	AccelGroupsFromObject(glib.Object) glib.SList
	AccelMapAddEntry(string, uint, gdk.ModifierType)
	AccelMapAddFilter(string)
	AccelMapChangeEntry(string, uint, gdk.ModifierType, bool) bool
	AccelMapGet() AccelMap
	AccelMapLoad(string)
	AccelMapLoadFD(int)
	AccelMapLockPath(string)
	AccelMapLookupEntry(string) AccelKey
	AccelMapSave(string)
	AccelMapSaveFD(int)
	AccelMapUnlockPath(string)
	AcceleratorGetDefaultModMask() gdk.ModifierType
	AcceleratorGetLabel(uint, gdk.ModifierType) string
	AcceleratorName(uint, gdk.ModifierType) string
	AcceleratorParse(string) (uint, gdk.ModifierType)
	AcceleratorSetDefaultModMask(gdk.ModifierType)
	AcceleratorValid(uint, gdk.ModifierType) bool
	AddProviderForScreen(gdk.Screen, StyleProvider, uint)
	AdjustmentNew(float64, float64, float64, float64, float64, float64) (Adjustment, error)
	AppChooserButtonNew(string) (AppChooserButton, error)
	AppChooserDialogNewForContentType(Window, DialogFlags, string) (AppChooserDialog, error)
	AppChooserWidgetNew(string) (AppChooserWidget, error)
	ApplicationNew(string, glib.ApplicationFlags) (Application, error)
	ApplicationWindowNew(Application) (ApplicationWindow, error)
	AssistantNew() (Assistant, error)
	BoxNew(Orientation, int) (Box, error)
	BuilderNew() (Builder, error)
	ButtonNew() (Button, error)
	ButtonNewWithLabel(string) (Button, error)
	ButtonNewWithMnemonic(string) (Button, error)
	CalendarNew() (Calendar, error)
	CellRendererPixbufNew() (CellRendererPixbuf, error)
	CellRendererSpinnerNew() (CellRendererSpinner, error)
	CellRendererTextNew() (CellRendererText, error)
	CellRendererToggleNew() (CellRendererToggle, error)
	CheckButtonNew() (CheckButton, error)
	CheckButtonNewWithLabel(string) (CheckButton, error)
	CheckButtonNewWithMnemonic(string) (CheckButton, error)
	CheckMenuItemNew() (CheckMenuItem, error)
	CheckMenuItemNewWithLabel(string) (CheckMenuItem, error)
	CheckMenuItemNewWithMnemonic(string) (CheckMenuItem, error)
	CheckVersion(uint, uint, uint) error
	ClipboardGet(gdk.Atom) (Clipboard, error)
	ClipboardGetForDisplay(gdk.Display, gdk.Atom) (Clipboard, error)
	ColorButtonNew() (ColorButton, error)
	ColorButtonNewWithRGBA(gdk.RGBA) (ColorButton, error)
	ColorChooserDialogNew(string, Window) (ColorChooserDialog, error)
	ComboBoxNew() (ComboBox, error)
	ComboBoxNewWithEntry() (ComboBox, error)
	ComboBoxNewWithModel(TreeModel) (ComboBox, error)
	ComboBoxTextNew() (ComboBoxText, error)
	ComboBoxTextNewWithEntry() (ComboBoxText, error)
	CssProviderGetDefault() (CssProvider, error)
	CssProviderGetNamed(string, string) (CssProvider, error)
	CssProviderNew() (CssProvider, error)
	DialogNew() (Dialog, error)
	DrawingAreaNew() (DrawingArea, error)
	EntryBufferNew(string, int) (EntryBuffer, error)
	EntryNew() (Entry, error)
	EntryNewWithBuffer(EntryBuffer) (Entry, error)
	EventBoxNew() (EventBox, error)
	EventsPending() bool
	ExpanderNew(string) (Expander, error)
	FileChooserButtonNew(string, FileChooserAction) (FileChooserButton, error)
	FileChooserDialogNewWith1Button(string, Window, FileChooserAction, string, ResponseType) (FileChooserDialog, error)
	FileChooserDialogNewWith2Buttons(string, Window, FileChooserAction, string, ResponseType, string, ResponseType) (FileChooserDialog, error)
	FileChooserWidgetNew(FileChooserAction) (FileChooserWidget, error)
	FileFilterNew() (FileFilter, error)
	FontButtonNew() (FontButton, error)
	FontButtonNewWithFont(string) (FontButton, error)
	FrameNew(string) (Frame, error)
	GdkCairoSetSourcePixBuf(cairo.Context, gdk.Pixbuf, float64, float64)
	GetMajorVersion() uint
	GetMicroVersion() uint
	GetMinorVersion() uint
	GridNew() (Grid, error)
	IconThemeGetDefault() (IconTheme, error)
	IconThemeGetForScreen(gdk.Screen) (IconTheme, error)
	IconViewNew() (IconView, error)
	IconViewNewWithModel(TreeModel) (IconView, error)
	ImageNew() (Image, error)
	ImageNewFromFile(string) (Image, error)
	ImageNewFromIconName(string, IconSize) (Image, error)
	ImageNewFromPixbuf(gdk.Pixbuf) (Image, error)
	ImageNewFromResource(string) (Image, error)
	InfoBarNew() (InfoBar, error)
	Init(*[]string)
	LabelNew(string) (Label, error)
	LabelNewWithMnemonic(string) (Label, error)
	LayoutNew(Adjustment, Adjustment) (Layout, error)
	LevelBarNew() (LevelBar, error)
	LevelBarNewForInterval(float64, float64) (LevelBar, error)
	LinkButtonNew(string) (LinkButton, error)
	LinkButtonNewWithLabel(string, string) (LinkButton, error)
	ListStoreNew(...glib.Type) (ListStore, error)
	Main()
	MainIteration() bool
	MainIterationDo(bool) bool
	MainQuit()
	MenuBarNew() (MenuBar, error)
	MenuButtonNew() (MenuButton, error)
	MenuItemNew() (MenuItem, error)
	MenuItemNewWithLabel(string) (MenuItem, error)
	MenuItemNewWithMnemonic(string) (MenuItem, error)
	MenuNew() (Menu, error)
	MessageDialogNew(Window, DialogFlags, MessageType, ButtonsType, string, ...interface{}) MessageDialog
	MessageDialogNewWithMarkup(Window, DialogFlags, MessageType, ButtonsType, string, ...interface{}) MessageDialog
	NotebookNew() (Notebook, error)
	OffscreenWindowNew() (OffscreenWindow, error)
	PanedNew(Orientation) (Paned, error)
	ProgressBarNew() (ProgressBar, error)
	RadioButtonNew(glib.SList) (RadioButton, error)
	RadioButtonNewFromWidget(RadioButton) (RadioButton, error)
	RadioButtonNewWithLabel(glib.SList, string) (RadioButton, error)
	RadioButtonNewWithLabelFromWidget(RadioButton, string) (RadioButton, error)
	RadioButtonNewWithMnemonic(glib.SList, string) (RadioButton, error)
	RadioButtonNewWithMnemonicFromWidget(RadioButton, string) (RadioButton, error)
	RadioMenuItemNew(glib.SList) (RadioMenuItem, error)
	RadioMenuItemNewFromWidget(RadioMenuItem) (RadioMenuItem, error)
	RadioMenuItemNewWithLabel(glib.SList, string) (RadioMenuItem, error)
	RadioMenuItemNewWithLabelFromWidget(RadioMenuItem, string) (RadioMenuItem, error)
	RadioMenuItemNewWithMnemonic(glib.SList, string) (RadioMenuItem, error)
	RadioMenuItemNewWithMnemonicFromWidget(RadioMenuItem, string) (RadioMenuItem, error)
	RecentFilterNew() (RecentFilter, error)
	RecentManagerGetDefault() (RecentManager, error)
	RemoveProviderForScreen(gdk.Screen, StyleProvider)
	ScaleButtonNew(IconSize, float64, float64, float64, []string) (ScaleButton, error)
	ScaleNew(Orientation, Adjustment) (Scale, error)
	ScaleNewWithRange(Orientation, float64, float64, float64) (Scale, error)
	ScrollbarNew(Orientation, Adjustment) (Scrollbar, error)
	ScrolledWindowNew(Adjustment, Adjustment) (ScrolledWindow, error)
	SearchEntryNew() (SearchEntry, error)
	SeparatorMenuItemNew() (SeparatorMenuItem, error)
	SeparatorNew(Orientation) (Separator, error)
	SeparatorToolItemNew() (SeparatorToolItem, error)
	SettingsGetDefault() (Settings, error)
	SpinButtonNew(Adjustment, float64, uint) (SpinButton, error)
	SpinButtonNewWithRange(float64, float64, float64) (SpinButton, error)
	SpinnerNew() (Spinner, error)
	StatusbarNew() (Statusbar, error)
	StyleContextResetWidgets(gdk.Screen)
	SwitchNew() (Switch, error)
	TargetEntryNew(string, TargetFlags, uint) (TargetEntry, error)
	TextBufferNew(TextTagTable) (TextBuffer, error)
	TextTagNew(string) (TextTag, error)
	TextTagTableNew() (TextTagTable, error)
	TextViewNew() (TextView, error)
	TextViewNewWithBuffer(TextBuffer) (TextView, error)
	ToggleButtonNew() (ToggleButton, error)
	ToggleButtonNewWithLabel(string) (ToggleButton, error)
	ToggleButtonNewWithMnemonic(string) (ToggleButton, error)
	ToolButtonNew(Widget, string) (ToolButton, error)
	ToolItemNew() (ToolItem, error)
	TreeIterNew() TreeIter
	ToolbarNew() (Toolbar, error)
	TreePathFromList(glib.List) TreePath
	TreePathNew() TreePath
	TreePathNewFromString(string) (TreePath, error)
	TreeStoreNew(...glib.Type) (TreeStore, error)
	TreeViewColumnNew() (TreeViewColumn, error)
	TreeViewColumnNewWithAttribute(string, CellRenderer, string, int) (TreeViewColumn, error)
	TreeViewNew() (TreeView, error)
	TreeViewNewWithModel(TreeModel) (TreeView, error)
	ViewportNew(Adjustment, Adjustment) (Viewport, error)
	VolumeButtonNew() (VolumeButton, error)
	WindowGetDefaultIconName() (string, error)
	WindowNew(WindowType) (Window, error)
	WindowSetDefaultIcon(gdk.Pixbuf)
	WindowSetDefaultIconFromFile(string) error
	WindowSetDefaultIconName(string)
} // end of Gtk

func AssertGtk(_ Gtk) {}
