package cairof

// #cgo pkg-config: cairo cairo-gobject
// #include <stdlib.h>
// #include <cairo.h>
// #include <cairo-gobject.h>
import "C"
import (
	"unsafe"

	"github.com/gotk3/gotk3/cairo"
)

func init() {
	cairo.STATUS_SUCCESS = C.CAIRO_STATUS_SUCCESS
	cairo.STATUS_NO_MEMORY = C.CAIRO_STATUS_NO_MEMORY
	cairo.STATUS_INVALID_RESTORE = C.CAIRO_STATUS_INVALID_RESTORE
	cairo.STATUS_INVALID_POP_GROUP = C.CAIRO_STATUS_INVALID_POP_GROUP
	cairo.STATUS_NO_CURRENT_POINT = C.CAIRO_STATUS_NO_CURRENT_POINT
	cairo.STATUS_INVALID_MATRIX = C.CAIRO_STATUS_INVALID_MATRIX
	cairo.STATUS_INVALID_STATUS = C.CAIRO_STATUS_INVALID_STATUS
	cairo.STATUS_NULL_POINTER = C.CAIRO_STATUS_NULL_POINTER
	cairo.STATUS_INVALID_STRING = C.CAIRO_STATUS_INVALID_STRING
	cairo.STATUS_INVALID_PATH_DATA = C.CAIRO_STATUS_INVALID_PATH_DATA
	cairo.STATUS_READ_ERROR = C.CAIRO_STATUS_READ_ERROR
	cairo.STATUS_WRITE_ERROR = C.CAIRO_STATUS_WRITE_ERROR
	cairo.STATUS_SURFACE_FINISHED = C.CAIRO_STATUS_SURFACE_FINISHED
	cairo.STATUS_SURFACE_TYPE_MISMATCH = C.CAIRO_STATUS_SURFACE_TYPE_MISMATCH
	cairo.STATUS_PATTERN_TYPE_MISMATCH = C.CAIRO_STATUS_PATTERN_TYPE_MISMATCH
	cairo.STATUS_INVALID_CONTENT = C.CAIRO_STATUS_INVALID_CONTENT
	cairo.STATUS_INVALID_FORMAT = C.CAIRO_STATUS_INVALID_FORMAT
	cairo.STATUS_INVALID_VISUAL = C.CAIRO_STATUS_INVALID_VISUAL
	cairo.STATUS_FILE_NOT_FOUND = C.CAIRO_STATUS_FILE_NOT_FOUND
	cairo.STATUS_INVALID_DASH = C.CAIRO_STATUS_INVALID_DASH
	cairo.STATUS_INVALID_DSC_COMMENT = C.CAIRO_STATUS_INVALID_DSC_COMMENT
	cairo.STATUS_INVALID_INDEX = C.CAIRO_STATUS_INVALID_INDEX
	cairo.STATUS_CLIP_NOT_REPRESENTABLE = C.CAIRO_STATUS_CLIP_NOT_REPRESENTABLE
	cairo.STATUS_TEMP_FILE_ERROR = C.CAIRO_STATUS_TEMP_FILE_ERROR
	cairo.STATUS_INVALID_STRIDE = C.CAIRO_STATUS_INVALID_STRIDE
	cairo.STATUS_FONT_TYPE_MISMATCH = C.CAIRO_STATUS_FONT_TYPE_MISMATCH
	cairo.STATUS_USER_FONT_IMMUTABLE = C.CAIRO_STATUS_USER_FONT_IMMUTABLE
	cairo.STATUS_USER_FONT_ERROR = C.CAIRO_STATUS_USER_FONT_ERROR
	cairo.STATUS_NEGATIVE_COUNT = C.CAIRO_STATUS_NEGATIVE_COUNT
	cairo.STATUS_INVALID_CLUSTERS = C.CAIRO_STATUS_INVALID_CLUSTERS
	cairo.STATUS_INVALID_SLANT = C.CAIRO_STATUS_INVALID_SLANT
	cairo.STATUS_INVALID_WEIGHT = C.CAIRO_STATUS_INVALID_WEIGHT
	cairo.STATUS_INVALID_SIZE = C.CAIRO_STATUS_INVALID_SIZE
	cairo.STATUS_USER_FONT_NOT_IMPLEMENTED = C.CAIRO_STATUS_USER_FONT_NOT_IMPLEMENTED
	cairo.STATUS_DEVICE_TYPE_MISMATCH = C.CAIRO_STATUS_DEVICE_TYPE_MISMATCH
	cairo.STATUS_DEVICE_ERROR = C.CAIRO_STATUS_DEVICE_ERROR
}

var key_Status = map[cairo.Status]string{

	cairo.STATUS_SUCCESS:                   "CAIRO_STATUS_SUCCESS",
	cairo.STATUS_NO_MEMORY:                 "CAIRO_STATUS_NO_MEMORY",
	cairo.STATUS_INVALID_RESTORE:           "CAIRO_STATUS_INVALID_RESTORE",
	cairo.STATUS_INVALID_POP_GROUP:         "CAIRO_STATUS_INVALID_POP_GROUP",
	cairo.STATUS_NO_CURRENT_POINT:          "CAIRO_STATUS_NO_CURRENT_POINT",
	cairo.STATUS_INVALID_MATRIX:            "CAIRO_STATUS_INVALID_MATRIX",
	cairo.STATUS_INVALID_STATUS:            "CAIRO_STATUS_INVALID_STATUS",
	cairo.STATUS_NULL_POINTER:              "CAIRO_STATUS_NULL_POINTER",
	cairo.STATUS_INVALID_STRING:            "CAIRO_STATUS_INVALID_STRING",
	cairo.STATUS_INVALID_PATH_DATA:         "CAIRO_STATUS_INVALID_PATH_DATA",
	cairo.STATUS_READ_ERROR:                "CAIRO_STATUS_READ_ERROR",
	cairo.STATUS_WRITE_ERROR:               "CAIRO_STATUS_WRITE_ERROR",
	cairo.STATUS_SURFACE_FINISHED:          "CAIRO_STATUS_SURFACE_FINISHED",
	cairo.STATUS_SURFACE_TYPE_MISMATCH:     "CAIRO_STATUS_SURFACE_TYPE_MISMATCH",
	cairo.STATUS_PATTERN_TYPE_MISMATCH:     "CAIRO_STATUS_PATTERN_TYPE_MISMATCH",
	cairo.STATUS_INVALID_CONTENT:           "CAIRO_STATUS_INVALID_CONTENT",
	cairo.STATUS_INVALID_FORMAT:            "CAIRO_STATUS_INVALID_FORMAT",
	cairo.STATUS_INVALID_VISUAL:            "CAIRO_STATUS_INVALID_VISUAL",
	cairo.STATUS_FILE_NOT_FOUND:            "CAIRO_STATUS_FILE_NOT_FOUND",
	cairo.STATUS_INVALID_DASH:              "CAIRO_STATUS_INVALID_DASH",
	cairo.STATUS_INVALID_DSC_COMMENT:       "CAIRO_STATUS_INVALID_DSC_COMMENT",
	cairo.STATUS_INVALID_INDEX:             "CAIRO_STATUS_INVALID_INDEX",
	cairo.STATUS_CLIP_NOT_REPRESENTABLE:    "CAIRO_STATUS_CLIP_NOT_REPRESENTABLE",
	cairo.STATUS_TEMP_FILE_ERROR:           "CAIRO_STATUS_TEMP_FILE_ERROR",
	cairo.STATUS_INVALID_STRIDE:            "CAIRO_STATUS_INVALID_STRIDE",
	cairo.STATUS_FONT_TYPE_MISMATCH:        "CAIRO_STATUS_FONT_TYPE_MISMATCH",
	cairo.STATUS_USER_FONT_IMMUTABLE:       "CAIRO_STATUS_USER_FONT_IMMUTABLE",
	cairo.STATUS_USER_FONT_ERROR:           "CAIRO_STATUS_USER_FONT_ERROR",
	cairo.STATUS_NEGATIVE_COUNT:            "CAIRO_STATUS_NEGATIVE_COUNT",
	cairo.STATUS_INVALID_CLUSTERS:          "CAIRO_STATUS_INVALID_CLUSTERS",
	cairo.STATUS_INVALID_SLANT:             "CAIRO_STATUS_INVALID_SLANT",
	cairo.STATUS_INVALID_WEIGHT:            "CAIRO_STATUS_INVALID_WEIGHT",
	cairo.STATUS_INVALID_SIZE:              "CAIRO_STATUS_INVALID_SIZE",
	cairo.STATUS_USER_FONT_NOT_IMPLEMENTED: "CAIRO_STATUS_USER_FONT_NOT_IMPLEMENTED",
	cairo.STATUS_DEVICE_TYPE_MISMATCH:      "CAIRO_STATUS_DEVICE_TYPE_MISMATCH",
	cairo.STATUS_DEVICE_ERROR:              "CAIRO_STATUS_DEVICE_ERROR",
}

func StatusToString(status cairo.Status) string {

	s, ok := key_Status[status]
	if !ok {
		s = "CAIRO_STATUS_UNDEFINED"
	}

	return s
}

func marshalStatus(p uintptr) (interface{}, error) {
	c := C.g_value_get_enum((*C.GValue)(unsafe.Pointer(p)))
	return cairo.Status(c), nil
}
